# Generated by Django 3.1.7 on 2021-03-04 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_sportnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 4, 18, 51, 21, 767840, tzinfo=utc)),
        ),
    ]
